apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: {{APP}}
    name: {{APP}}
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: {{APP}}
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
    progressDeadlineSeconds: 21600
    template:
      metadata:
        labels:
          app: {{APP}}
      spec:
        containers:
        - env:
          - name: no_proxy
            value: localhost,127.0.0.1,{{NO_PROXY_DOMAINS}}
          - name: NO_PROXY
            value: localhost,127.0.0.1,{{NO_PROXY_DOMAINS}}
          - name: HTTP_PROXY
            value: '{{HTTP_PROXY_URL}}'
          - name: https_proxy
            value: '{{HTTP_PROXY_URL}}'
          - name: http_proxy
            value: '{{HTTP_PROXY_URL}}'
          - name: HTTPS_PROXY
            value: '{{HTTP_PROXY_URL}}'
          - name: TZ
            value: Europe/Madrid
          - name: JAVA_OPTS
            value: -Xms512m -Xmx1536m -Dspring.config.additional-location=file:///usr/local/tomcat/shared/conf/application.yaml -Djavax.net.ssl.trustStore=/secret/trustore/trustore-global.jks -Djavax.net.ssl.trustStorePassword=changeit
          resources:
            requests:
             memory: 1Gi
            limits:
              memory: 2Gi
          image: image-registry.openshift-image-registry.svc:5000/{{NAMESPACE}}/{{APP}}:latest
          imagePullPolicy: Always
          name: {{APP}}
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          volumeMounts:
          - name: {{APP}}-shared
            mountPath: /usr/local/tomcat/shared/conf/application.yaml
            subPath: application.yaml
            readOnly: true
          - name: {{APP}}-tomcat-conf
            mountPath: /usr/local/tomcat/conf
            readOnly: true
          - name: certificate-ssl
            mountPath: /secret
            readOnly: true
          - name: trustore-secret
            mountPath: /secret/trustore
            readOnly: true
          - name: {{APP}}-credentials-audit
            mountPath: /usr/local/tomcat/shared/conf/{{APP}}-credentials-audit.yaml
            subPath: {{APP}}-credentials-audit.yaml
            readOnly: true
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        volumes:
          - name: {{APP}}-tomcat-conf
            configMap:
              name: {{APP}}-tomcat-conf
          - name: {{APP}}-shared
            configMap:
              name: {{APP}}-shared
          - name: certificate-ssl
            secret:
              defaultMode: 420
              secretName: certificate-ssl
          - name: trustore-secret
            secret:
              defaultMode: 420
              secretName: trustore-global
          - name: {{APP}}-credentials-audit
            secret:
              defaultMode: 420
              secretName: {{APP}}-credentials-audit

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: {{APP}}
    name: {{APP}}
  spec:
    ports:
    - name: {{APP}}
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: {{APP}}-ssl
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      app: {{APP}}
    sessionAffinity: None
    type: ClusterIP
